services:
  fliq-widgets-preview:
    build:
      context: .
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_Y2xlcmsuZXhhbXBsZS5jb20k
    environment:
      CLERK_SECRET_KEY: sk_test_Y2xlcmsuZXhhbXBsZS5jb20kZHVtbXlwcmV2aWV3
    networks: [web]
    labels:
      - traefik.enable=true
      - "traefik.http.routers.fliqwidgets.rule=Host(`fliq-widgets.night.enkiduck.com`)"
      - traefik.http.routers.fliqwidgets.entrypoints=websecure
      - traefik.http.routers.fliqwidgets.tls.certresolver=le
      - traefik.http.services.fliqwidgets.loadbalancer.server.port=3000
networks:
  web:
    external: true
